
[toggles]
	# default: false
	autoAfk = false
	# default: false
	reconnectEnabled = false
	# default: false
	damageLogoutEnabled = false
	# default: true
	featuresEnabledIndicator = false

[configurations]
	# default: 300
	autoAfkTimerSeconds = 300
	# default: false
	reconnectOnDamageLogout = false
	# default: 3
	secondsBetweenReconnectAttempts = 10
	# default: 10
	reconnectAttemptNumber = 0
	# default: 20
	damageLogoutTolerance = 20

