name = "Access Your Abilities"
author = "RhythmicSys"
version = "3.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f9b258e33a5a8c71ac2787ebaeb879c285607a9c6b2f114e478c01f1184397b"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
