name = "Access Your Abilities"
author = "RhythmicSys"
version = "3.0.0"
description = "Modpack designed for mobility and visual accessibility"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c49a7605915f9450dbcb4b505a1bb259b4f48d694ab96c8a1472f61f096dd79"

[versions]
minecraft = "1.19.3"
quilt = "0.18.3"

[options]
acceptable-game-versions = ["1.16.5", "1.19", "1.19.2", "1.19.3"]
